### ISSUE TITLE
Weechat crashes when loading python scripts with weecord loaded

### ISSUE THREAD

**Issue by Aerex** [terminal-discord/weechat-discord#12]
This is a great plugin but I noticed from the original codebase that the plugin has some memory issues when loading too many channels. How difficult would it be to add configuration to load only selected channels instead of all of them. It seems like when running this in tandem with Python causes kernel panics

**Comment by Noskcaj19** [comment]
Thanks for opening an issue, the original codebase had issues due to the single threaded nature of weechat.  I recently added synchronization, which has fixed nearly every memory issue I have encountered (the nicklist is currently causing issues).
Which Python plugins are causing issues for you?

**Comment by Noskcaj19** [comment]
As for loading the channels, currently when the plugin connects, it finds all of the users guilds and their channels, and adds them to the buflist. It only loads messages and members when you select the channel.

However, I do hope to add an option to hide certain channels and guilds soon.

**Comment by Aerex** [comment]
Thanks for the quick response. I was not able to pinpoint the exact plugin but it does seems that there is limit to the amount of python plugins I can load before i get a kernal panic. It would take about 5 plugins before weechat crashes. Weechat is running against python 2.7 if that helps.

**Comment by Noskcaj19** [comment]
Are you getting a kernel panic or a segfault?

**Comment by Aerex** [comment]
```
[2018-09-03 07:15:24] Reading configuration file autosort.conf
[2018-09-03 07:15:24] Writing configuration file autosort.conf
[2018-09-03 07:15:24] Reading configuration file lua.conf
[2018-09-03 07:15:24] Reading configuration file tcl.conf
[2018-09-03 07:15:24] Reading configuration file perl.conf
[2018-09-03 07:15:24] Reading configuration file script.conf
[2018-09-03 07:15:24] Reading configuration file fset.conf
[2018-09-03 07:15:54] Writing configuration file autosort.conf
[2018-09-03 07:16:21] Writing configuration file colorize_nicks.conf
[2018-09-03 07:16:21] Writing configuration file python.conf
[2018-09-03 07:17:26] Very bad, WeeChat is crashing (SIGSEGV received)...

****** WeeChat CRASH DUMP ******

gui_windows . . . . . . . . . : 0x55bd18716120
last_gui_window . . . . . . . : 0x55bd18716120
gui_current window. . . . . . : 0x55bd18716120
gui_windows_tree. . . . . . . : 0x55bd18749b90

[window (addr:0x55bd18716120)]
  number. . . . . . . : 1
  win_x . . . . . . . : 16
  win_y . . . . . . . : 0
  win_width . . . . . : 125
  win_height. . . . . : 28
  win_width_pct . . . : 100
  win_height_pct. . . : 100
  win_chat_x. . . . . : 16
  win_chat_y. . . . . : 1
- weechat_crash_20180903_6323.log 17/911
````

Here is a snippet from the crash log. It appears to be a segmentation fault.

**Comment by Noskcaj19** [comment]
Alright, I made a couple changes to the synchronization.  I can not get it segfault, see if it fixed your issue.

**Comment by Aerex** [comment]
Sorry for not responding earlier. I am still getting Segmentation fault after loading the python plugins. Doing the reverse helps when I add each python 
plugin individual but eventuall weechat crashes. Perhaps it is just my python configuration. Thanks for the help though.

**Comment by Aerex** [comment]
Great I appreciate it.

**Comment by Noskcaj19** [comment]
Well, I think I have traced it to autosort. Can you check if disabling autosort stops the crashes for you?  I'll look into what is causing the crash.

**Comment by Aerex** [comment]
It is better but it still crashes as you use weechat. I tried disabling any plugin that manipulates the buflist but no real change

**Comment by Noskcaj19** [comment]
Well, it looks like the issue comes from the thread synchronization code, which turns out to be flawed and is not doing its job.  Problem is, I don't really know how to fix it.  I've tried (and failed) a few times now.  I'll try and find a solution.

**Comment by Aerex** [comment]
Interesting. Thank you for looking into this.  If you get to a road block then that is fine.

**Comment by Noskcaj19** [comment]
I checked how weeslack does async, and it uses a timer to block the main thread every 10 seconds (well, they just added dynamic updates).  That's not something I would really like to do, but right now, I can't get anything else to work.  This is a pretty major issue, so I think I will implement the timer and see how it works.

**Comment by Noskcaj19** [comment]
Sorry that took awhile, but I think it's fixed.  I switched to the timer and (hopefully for real this time) fixed the synchronization code, and now it does not crash even with all the plugins you listed loaded.  See if it works for you.

**Comment by kageurufu** [comment]
These changes fixed the crash for me, thank you!
