### ISSUE TITLE
Design Decisions

### ISSUE THREAD

**Issue by Noskcaj19** [terminal-discord/weechat-discord#16]
Currently, this plugin attempts to force weechat to act like Discord, however, not everything can implemented like this (channel groups, etc).

It needs to be decided how to implement functionality, the options seem to be:
* Attempting to copy Discords design and functionality in every possible way
* Attempt a more irc like interface
  * Something like [bitlbee discord](https://github.com/sm00th/bitlbee-discord/)?
  * Or something new that incorporates weechats abilities and the structure of discord?

There is also the issue that I do not know anything about the "typical" weechat workflow, and I would welcome suggestions or ideas from anyone who uses weechat extensively.

**Comment by Wingysam** [comment]
+1 for IRC like interface.

**Comment by Noskcaj19** [comment]
I suppose this is solved with the Discord and IRC modes
