### ISSUE TITLE
connect reports Unknown command

### ISSUE THREAD

**Issue by louy2** [terminal-discord/weechat-discord#17]
I get this when I do `/discord connect` after setting token:

    weecord: Unknown command

```
macOS Mojave 10.14.3
weechat --version
2.4
beta-x86_64-apple-darwin (default)
rustc 1.33.0-beta.10 (bb2d0ea24 2019-02-23)
```

**Comment by Noskcaj19** [comment]
Interesting, that is the error message that the plugin prints when it can't match the text after `/discord`.  I cannot replicate that error, and it seems to properly strip whitespace.

Do you have any plugins installed? it's possible that could be causing the issue.

**Comment by louy2** [comment]
No, I am new to Weechat and weecord is the only plugin I have.

Also I am using Apple Terminal.

So far `connect`, `disconnect`, and `upload` return this unknown command error, but I can set `token`, and `autostart` and `noautostart` returns success message.

**Comment by louy2** [comment]
LOL I think I am on the wrong branch. Now that I read the code it indeed doesn't have those three implemented.

**Comment by louy2** [comment]
I am on the wrong repo! LOL
I cloned weechat-discord-ng instead of this.
Didn't expect that one to be so alpha. XD

**Comment by Noskcaj19** [comment]
Ah, sorry about ng, it was an experiment and should probably not be public.
