### ISSUE TITLE
Message editing and deletion

### ISSUE THREAD

**Issue by Noskcaj19** [terminal-discord/weechat-discord#21]
Add support for editing and deleting messages, probably using a sed syntax similar to wee-slack

**Comment by mqp** [comment]
(Maybe it goes without saying, but there should also be support for showing when other people edit and delete their messages.)

**Comment by Noskcaj19** [comment]
That's probably good to note.  It should be able to be implemented quite easily once there I write a hdata api.

**Comment by Noskcaj19** [comment]
Support for message editing and deletion has been added, but displaying when other users do so could be tricky because the gateway doesn't provide much information about the events.

**Comment by Noskcaj19** [comment]
There is also the question of what should be shown when an edit is made.  The official client just adds a `(edited)` marker and does nothing for deleted messages, which would probably be sufficient.

From what I understand, lines cannot actually be deleted from buffers, just edited, so perhaps appending or overwriting `(deleted)` might work well for us.

**Comment by h1nk** [comment]
I'm a fan of the idea of trying to mimic as much of the Electron client's behavior as possible in a curses environment. Changing the message buffer line and appending a grey colored `(edited)` sounds the great. For messages that are deleted it's probably best to do what you mention and just say `(deleted)` stylized in the same way as `(edited)`. Editing a sent message to the contents of nothing is the same thing as deleting a message so this actually makes quite a lot of sense.

**Comment by Noskcaj19** [comment]
Now that I have a functioning hdata api, I have done some work towards displaying updates, and can successfully update simple single line messages.

The current issues are that weechat does not allow inserting or removing lines in regular buffers and updating the content of multiline messages is tricky.  The two options to fix the first issue is either clearing and re-adding the messages on such an update (most likely), or instead use a free text buffer and implement all text rendering from scratch.

Things todo:

- [ ] Extract text rendering (also needed for pinning ui)
- [ ] Use `message_printed` to store discords message id for messages (sort of done)
- [ ] Be able to diff printed messages to the updated form and decide to re-render (if another plugin prints to the buffer it would probably make this much more difficult [detecting foreign lines might work])
