### ISSUE TITLE
/query command overwritten

### ISSUE THREAD

**Issue by antoyo** [terminal-discord/weechat-discord#25]
Hi.
It seems that this plugin overwrite the `/query` command for non-discord channel.
For instance, if I do `/query username` on an IRC buffer, the status buffer reports:
```
weecord: Could not find user "username"
```
Thanks to fix this issue.

**Comment by Noskcaj19** [comment]
Can you see if this happens on master? This should have been fixed in db5a22c

**Comment by antoyo** [comment]
You're right. That's already fixed.
