### ISSUE TITLE
Typing notifications seem very spammy

### ISSUE THREAD

**Issue by mqp** [terminal-discord/weechat-discord#28]
It seems to me like the implementation of the "so-and-so is typing" indicator is that when someone starts typing, you print a typing notification message to the buffer with the channel they are typing into, and that's about all there is to it. Notably, the typing notification message doesn't seem to get cleared if they stop typing, or if new messages arrive in the channel.

This seems very spammy -- in my experience so far, typing notification messages soon comprise a majority of messages visible in a buffer. Am I missing something obvious?

I personally like wee-slack's implementation, where a sigil in the channel list serves as a "someone is typing" indicator, and details about who is typing go into the status bar.

**Comment by Noskcaj19** [comment]
So this was supposed to be a very temporary solution as much of the apis for bar items has not been added to the ffi yet.
I will set this behavior behind an option (defaulting to off) for now.

**Comment by Noskcaj19** [comment]
Typing messages will now only be printed if `plugins.var.weecord.typing_messages` is set to `true` until I can add the bar item.

**Comment by Noskcaj19** [comment]
The new bar item `discord_typing` should show the users currently typing.

I'm not sure about the channel list sigil though, I don't see anything like that in wee-slack.
