### ISSUE TITLE
Tracking last read content across clients

### ISSUE THREAD

**Issue by mqp** [terminal-discord/weechat-discord#32]
If I use the first-party Discord client on my phone and I read a message in some channel, and then I open it on my desktop, it knows what messages I have and haven't read on my phone. In fact, it stays up to date in roughly real time as I read messages on one device or another.

I'm not sure what technique the first-party client uses to do this -- I don't see anything in the documented API. But it would certainly be a nice quality of life feature for this plugin if it's possible to replicate, so that the unread channel indicators can retain their meaning.

**Comment by Noskcaj19** [comment]
Discord uses the undocumented `read_state` field and /ack endpoint for this.  #29 should solve this

**Comment by Noskcaj19** [comment]
This should now be implemented in da300dd.
