### ISSUE TITLE
Indicating when other users are typing

### ISSUE THREAD

**Issue by h1nk** [terminal-discord/weechat-discord#46]
It would be nice if there was a way to know when other users are typing like in the Electron client. Perhaps displaying some text in the status bar (below the chat area and above the input bar) like:

- ••• **user1** is typing...
- ••• **user1**, **user2** and **user3** are typing...
- ••• Several people are typing...

It would even be possible to mimic the ellipsis spinner by cycling between slightly different colors with the three leading dots or even creating a different spinner pattern using `●` & `•`.

**Comment by Noskcaj19** [comment]
So this has actually already been added (although not the animated ellipsis) with the `discord_typing` bar item.  Weecord will report your typing status to discord if the `plugins.var.weecord.send_typing_events` var is set to `true`.

I don't believe any of this is documented though.... I need to add some documentation.

**Comment by h1nk** [comment]
Thanks a lot! The bar item functions properly. As an improvement it might be nicer to mimic the Electron client's way of showing the list of currently typing users more closely like I stated earlier.

Also I think `plugins.var.weecord.autostart` & `plugins.var.weecord.send_typing_events` might make more sense as boolean configuration options rather than strings.

**Comment by Noskcaj19** [comment]
I believe I copied the typing list format from weeslack but I plan to add an option to let that be changed.

I am going to rewrite the way options are handled soon which will let me use bools.

**Comment by Noskcaj19** [comment]
The options are now all properly typed.
