### ISSUE TITLE
Plugin not working currently

### ISSUE THREAD

**Issue by h1nk** [terminal-discord/weechat-discord#51]
I updated from ce64521 to the latest master commit and I'm no longer able to get the plugin functioning. It says I'm "Already connected" but I'm not getting anything in my buflist with discord-mode set. Is the plugin currently in a working state?

**Comment by Noskcaj19** [comment]
Are you using IRC mode?  Making the change from untyped to typed options changed the path of config variables, ie `plugins.var.weecord` is now `weecord.main`.

I suspect because of this it cannot find your token, and is giving you a strange error message.

**Comment by Noskcaj19** [comment]
Actually, it should be fairly easy to add a migration command.

**Comment by h1nk** [comment]
I nuked my `~/.config/weechat/` and reinstalled the plugin just to see if would change anything but still can't seem to get it to work. I have both `plugins.var.weecord.token` and `weecord.main.token` set to `${sec.data.discord_token}` and have the secured data entry for `discord_token` set to a Discord token I pulled from Local Storage in a browser session.

**Comment by h1nk** [comment]
I also just noticed the plugin prints just the word `false` just before `Plugins loaded: ...` in the `1.weechat buffer`.

**Comment by Noskcaj19** [comment]
Alright, that's strange. I'll take a look.

**Comment by Noskcaj19** [comment]
So, I found where the print is coming from (debug print I forgot to remove), but I cannot seem to reproduce it not connecting, even on a clean config dir.

**Comment by Noskcaj19** [comment]
The only thing I can think of would be [src/buffers.rs:104](https://github.com/terminal-discord/weechat-discord/blob/master/src/buffers.rs#L104).  Reading it I'm not sure why its a return, maybe try changing that to a `continue` and see what happens?

**Comment by h1nk** [comment]
This is indeed very strange. I ran through the same steps in a Docker container to ensure I could really reproduce the problem in a clean environment and the same thing happened using these steps for a typical WeeChat install on a Ubuntu system:
```bash
docker run --rm -it ubuntu
apt update
apt install -y gpg ca-certificates
apt-key adv --keyserver hkps://keys.openpgp.org --recv-keys 11E9DE8848F2B65222AA75B8D1820DB22A11534E
echo "deb https://weechat.org/ubuntu bionic main" | tee /etc/apt/sources.list.d/weechat.list
cat /etc/apt/sources.list.d/weechat.list
apt update
apt show weechat
apt install -y dirmngr gpg-agent apt-transport-https weechat weechat-dev git make cargo clang
weechat --version && weechat -r /quit
cd /tmp/
git clone https://github.com/terminal-discord/weechat-discord.git
cd ./weechat-discord/
make install
weechat # /set weecord.main.token "..." & /discord connect
```
I'm getting the Discord token via a Firefox login session and then Dev Tools > Storage > Local Storage > `token`. I also tried with the edit you suggested, changing the `return` on [src/buffers.rs:104](https://github.com/terminal-discord/weechat-discord/blob/master/src/buffers.rs#L104) to an unconditional `continue`:
```diff
diff --git a/src/buffers.rs b/src/buffers.rs
index 463d980..003c03d 100644
--- a/src/buffers.rs
+++ b/src/buffers.rs
@@ -101,7 +101,7 @@ pub fn create_buffers_from_flat_items(
             (Some(guild_id), channels) => {
                 let guild = match guild_id.to_guild_cached(&ctx.cache) {
                     Some(guild) => guild,
-                    None => return,
+                    None => continue,
                 };
                 let guild = guild.read();
 
```
 Unfortunately after re-`make install`ing there wasn't any change. I also inspected the Discord token value to make sure I wasn't including the quotes as part of the value itself.

**Comment by Noskcaj19** [comment]
Alright, that's very strange.  The only thing I can think of is that Discord is sending you data in a way it doesn't for me, and because I depend on a number of undocumented apis, that has caused breakage in the past.

Alternatively, you wouldn't happen to have nitro, be in a very large (30+?) number of servers, or anything else different from a generic Discord account?

**Comment by h1nk** [comment]
I am in a large number of servers, definitely more than 30+ guilds.

**Comment by Noskcaj19** [comment]
Well, weecord makes a _lot_ of assumptions (for various reasons), but one of them is essentially that all guilds will be cached.  I wonder if discord is not sending guild data because you are in so many.  I know discord recently removed an undocumented op to fetch all guilds, and have switched to a more nuanced system for lazily loading guilds, and I haven't had the time to incorporate that (or even find out if its necessary).

**Comment by h1nk** [comment]
As a sanity check I wanted to try reverting to an older version of the plugin but it doesn't seem I can build from an older checkout anymore:

```
# git checkout -- ./
root@eaa3cfa9860d:/tmp/weechat-discord# git checkout ce64521
Note: checking out 'ce64521'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at ce64521 Make makefile respect `$WEECHAT_HOME`, fixes #45
# root@eaa3cfa9860d:/tmp/weechat-discord# make 
cargo build --release
    Updating crates.io index
    Updating git repository `https://github.com/terminal-discord/serenity`
error: failed to load source for a dependency on `serenity`

Caused by:
  Unable to update https://github.com/terminal-discord/serenity?rev=ff67eef

Caused by:
  revspec 'ff67eef' not found; class=Reference (4); code=NotFound (-3)
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 101
root@eaa3cfa9860d:/tmp/weechat-discord#
```

I don't know if Azure Pipelines still has build artifacts of older versions or if they expired, I can't seem to find them on the builds page.

**Comment by Noskcaj19** [comment]
Sorry about that, that's something I've worried would happen due to how I'm rebasing changes onto serenity.

It occurs to me one of the changes since your last install was f70173c, the change that removed the old sync op.  It's possible that it still functions...  I would try adding back what was removed in that commit, and leaving the chunk guilds function, and seeing if that works.

**Comment by Noskcaj19** [comment]
Actually, I believe it may be possible to compile old sources by patching the serenity dependency revision to the _current_ HEAD since there have been little or no breaking changes.

**Comment by Noskcaj19** [comment]
On the current master (65ecb7f) I am able to load 50+ very large guilds.  So I'm not entirely sure if there is something I haven't triggered on Discords backend or if it's a more specific issue.

**Comment by h1nk** [comment]
I can't seem to get the current master commit to compile due to some cargo compile dependencies failing:

```
error: enum variants on type aliases are experimental
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-rustls-0.10.2/src/lib.rs:260:9
    |
260 |         Self::Client(s)
    |         ^^^^^^^^^^^^

error: enum variants on type aliases are experimental
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-rustls-0.10.2/src/lib.rs:266:9
    |
266 |         Self::Server(s)
    |         ^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `tokio-rustls`.
warning: build failed, waiting for other jobs to finish...
error: build failed
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 101
```

**Comment by Noskcaj19** [comment]
Are you on the latest stable rustc?  CI compiled with 1.39.0 and passed.

**Comment by h1nk** [comment]
My `rustc` was outdated, thank you. It compiled and the plugin is now functioning well with the changes you made.
