### ISSUE TITLE
Kill the startup deadlock.

### ISSUE THREAD

**Issue by Noskcaj19** [terminal-discord/weechat-discord#53]
If a channel is opened while the buffers are being added at startup weechat will fairly reliably deadlock.

This is probably due to serenity repeatedly obtaining locks while updating the cache with GUILD_MEMBER_CHUNK events.

**Comment by antoyo** [comment]
Is this what is causing the discord channels to not load without any error message?

**Comment by Noskcaj19** [comment]
Are you in more than 20-30 or so guilds? I believe that is a separate issue related to how Discord handles sending data to users with large amounts of guilds and users (I've just made #54 for that).

**Comment by antoyo** [comment]
Actually, it seems to have been cause by a change of settings during the last upgrade.
I set again my token and it now works.

**Comment by Noskcaj19** [comment]
Ah, the setting paths were changed when I switched from plugin options to a proper config file, sorry about that.

**Comment by Noskcaj19** [comment]
This seems to have been caused by the writer starvation prevention in parking_lot.  I have tried to patch serenity and weecord to disable that feature and it seems to have fixed the issue.
