### ISSUE TITLE
Secured Token not working.

### ISSUE THREAD

**Issue by sw1tch-bl4d3** [terminal-discord/weechat-discord#60]
OS: Arch Linux (5.4.2-arch1-1)
Weechat: 2.8-dev

Hello,
I tried to use the secure token storage but it seems that weecord cant read it.
If I do `/discord token <token>` then I can connect with `/discord connect`
But if I do `/secure set discord_token <token>`,then do `/discord token ${sec.data.discord_token}` and then `/discord connect` it just doesnt respond.
No error message in the weechat buffer.
If I try to do /discord connect a 2nd time it says: `discord: Already connected`.
I am in discord-mode 

Help would be appreciated!

**Comment by Noskcaj19** [comment]
That's strange, I cannot replicate that on HEAD with weechat 2.6.  I'll see if it's an issue with 2.8.

**Comment by Noskcaj19** [comment]
I just realized, the secure data is only loaded on auto connect.  The `connect` command doesn't try to load secure data.

**Comment by sw1tch-bl4d3** [comment]
Nope, `/discord autostart` and then restarting doesnt fix the problem, the same thing happens. @Noskcaj19

**Comment by sw1tch-bl4d3** [comment]
Ah wait, i should update my weechat-discord!

**Comment by sw1tch-bl4d3** [comment]
Yep, https://github.com/terminal-discord/weechat-discord/commit/f9eb60e04f140dc418b21734f37ed4fd15d591a2 fixed it! Thanks!
