### ISSUE TITLE
/Query does not update with messages

### ISSUE THREAD

**Issue by Brando753** [terminal-discord/weechat-discord#61]
When you enter a DM with another user using /query the chat history loads, however anything new that is entered including your own replies is not displayed. So far the only way to see what has been said in a DM since you open the buffer is to close the buffer and reopen with /query.

**Comment by Noskcaj19** [comment]
That is very strange, I also cannot replicate that behavior on master.  Could you check if it happens with all other scripts unloaded?

**Comment by Brando753** [comment]
Reran weechat with -s and the issue is not showing up, will explore what might be causing the issue.

**Comment by Noskcaj19** [comment]
What scripts do you have installed?

**Comment by Brando753** [comment]
So after running with all scripts disabled I slowly turned on each script and could not get the issue to reoccur. I finally just restarted the client with everything running and once again could not get the issue to reoccur, I will document what plugins and scripts I have here for reference sake but will close the issue out as I can no longer reproduce it. 

`Plugins loaded:
  weecord: Discord integration for weechat
  alias: Alias commands
  python: Support of python scripts
  script: Script manager
  spell: Spell checker for input
  exec: Execution of external commands in WeeChat
  fset: Fast set of WeeChat and plugins options
  ruby: Support of ruby scripts 
  fifo: FIFO pipe for remote control
  buflist: Buffers list
  trigger: Text replacement and command execution on events triggered by WeeChat/plugins
  irc: IRC (Internet Relay Chat) protocol
  logger: Log buffers to files
  charset: Charset conversions
  relay: Relay WeeChat data to remote application (irc/weechat protocols)
  xfer: DCC file transfer and direct chat
  perl: Support of perl scripts

perl scripts loaded:
  beep v1.1 - Beep (terminal bell) and/or run command on highlight/private message or new DCC

ruby scripts loaded:
  (none)

python scripts loaded:
  chanop v0.2.6 - Helper script for IRC Channel Operators
  chanstat v0.1 - Channel statistics
  country v0.5 - Prints user's country and local time in whois replies
  leet v0.1 - Convert text to leet
  prism v0.2.1 - Taste the rainbow. 
  shell v0.5 - Run shell commands in WeeChat
  upside_down v0.3 - Replaces text you write with upside down text
  urlbar v12 - Bar with URLs. For easy clicking or selecting.
  urlgrab v2.7 - Url functionality Loggin, opening of browser, selectable links
  weeget v1.8 - WeeChat scripts manager
`
