### ISSUE TITLE
Panic when loading into guild channels

### ISSUE THREAD

**Issue by mjsir911** [terminal-discord/weechat-discord#63]
Hi,

Recently when moving to any discord buffer the client errors out and discord then locks me out until I verify my email.

The output is a bit scrombled because it's outputting directly in weechat:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Http(UnsuccessfulRequest(ErrorResponse { status_code: 403, url: "https://discordapp.com/api/v6/guilds/239747893706096650/members?&limit=1000", error: "Missing Access" }))', src/libcore/result.rs:999:5
                                                                                                                    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
                                                   thread '<unnamed>' panicked at 'Unable to fetch guilds: Http(UnsuccessfulRequest(ErrorResponse { status_code: 403, url: "https://discordapp.com/api/v6/users/@me/guilds?limit=100&&after=1", error: "You need to verify your account in order to perform this action." }))', src/libcore/result.rs:999:5
```

This didn't happen before, so it's definitely a new thing.

Of note is that private messages work fine.

Let me know if I can do anything, Thanks

**Comment by Noskcaj19** [comment]
Are you using the latest version? This _should_ have been fixed by 4357d56.

**Comment by mjsir911** [comment]
Thanks, that did it

Sorry for the dumb issue.

Is there any suggestion for automated updates? Typically I leave that up to my package manager, but I'm wondering how other's do it.

Thanks again

related: #62 ?

**Comment by Noskcaj19** [comment]
Well, it seems weechat may have an api for plugin updates that I will have to look into (#64).
