### ISSUE TITLE
Supporting DMs

### ISSUE THREAD

**Issue by skuzzymiglet** [terminal-discord/weechat-discord#73]
Is DM support planned?

**Comment by skuzzymiglet** [comment]
For those who need to know, you `\discord join` the user you want to DM

**Comment by Noskcaj19** [comment]
`/query` also works if you are in a Discord buffer

**Comment by skuzzymiglet** [comment]
When are DMs loaded? For me, they haven't loaded yet (after ~1min).

**Comment by Noskcaj19** [comment]
The contents of the buffer should load immediately.  However "Discord mode" does not automatically create DM buffers.  "irc-mode" can have a set of DMs to open automatically though.

**Comment by skuzzymiglet** [comment]
I am in IRC mode. The autocomplete won't load them and they don't work.
Servers are fine, however

**Comment by Noskcaj19** [comment]
Interesting, DMs should be able to be added to the autojoin/watch lists like any other server (it needs to be the DM id and not the user id, that ui is pretty rough).

The autocomplete issue my be related to #65 and the (apparent) changes around data loading.

I don't have a lot of time to look into this or the project right now sadly.
