### ISSUE TITLE
Typing indicator in bar.status

### ISSUE THREAD

**Issue by skuzzymiglet** [terminal-discord/weechat-discord#76]
It would be much cleaner to have the typing notifications in the status bar than breaking up text. Maybe a variable could be set?

Also, you could have a blinking `⬛` colored for the typing users. Maybe modes:

`full`: `SomeUser#1234`
`concise`: `⬛⬛⬛` (colored)
`concise-blink`: above but blinking
`number`: `3 typing`

**Comment by Noskcaj19** [comment]
This has actually been implemented for some time now as a bar item `discord_typing`.  Printing typing notifications to the buffer was an old temporary hack, that should be disabled by default with the `weecord.main.send_typing_events` option.

Honestly it should be completely removed.
