### ISSUE TITLE
Where are the so-called binairies ?

### ISSUE THREAD

**Issue by T0MuX** [terminal-discord/weechat-discord#79]
Hello, this is not an issue but a question.

On the readme ([this page](https://github.com/terminal-discord/weechat-discord)) it is wrote "Binaries are automatically compiled for macOS and linux on Github Actions".

"Github Actions" is pointing to https://github.com/terminal-discord/weechat-discord/actions ... but on this page, I can't find any binairies. Where are they ?

Thank you !

**Comment by Noskcaj19** [comment]
Github Actions aren't really intuitive, I should probably provide more detailed instructions.  On the "All workflows" page you linked, click on the latest build (or whatever build you want), the assets are there.

As far as I know, Github provides no way to link to the latest build.

**Comment by Noskcaj19** [comment]
I have changed the "Github Actions" link to a url that will redirect to the latest CI build page.

**Comment by T0MuX** [comment]
@Noskcaj19 Ah great ! Thank you !

**Comment by 097115** [comment]
@Noskcaj19 

> I have changed the "Github Actions" link to a url that will redirect to the latest CI build page.

The [link](https://terminal-discord.vercel.app/api/latest-build?repo=weechat-discord&workflow=1329556&branch=master&redirect) is broken?

![a](https://github.com/user-attachments/assets/5c1a361e-4334-40df-9f5a-893fdd713dfe)
