### ISSUE TITLE
does not build due to simple_ast dependencies

### ISSUE THREAD

**Issue by maygic23** [terminal-discord/weechat-discord#81]
1. cannot make before removing Cargo.lock - should be included in .gitignore?
2. cargo build fails as below:
raspberrypi% make
cargo build --release --verbose
warning: unused manifest key: package.edition
Updating git repository `https://github.com/terminal-discord/parking_lot`
Updating registry `https://github.com/rust-lang/crates.io-index`
Updating git repository `https://github.com/terminal-discord/rust-weechat`
Updating git repository `https://github.com/terminal-discord/serenity`
Updating git repository `https://github.com/Noskcaj19/simple-ast`
error: no matching package named `oniguruma` found (required by `simple_ast`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^4.3.2
versions found: 0.3.0, 0.2.0, 0.1.0
Makefile:7: polecenia dla obiektu 'all' nie powiodły się
make: *** [all] Błąd 101

raspberrypi% cargo install oniguruma
Updating registry `https://github.com/rust-lang/crates.io-index`
Downloading oniguruma v0.3.0
error: specified package has no binaries

raspberrypi% cargo install onig
Updating registry `https://github.com/rust-lang/crates.io-index`
Downloading onig v6.0.0
error: specified package has no binaries

**Comment by Noskcaj19** [comment]
That is quite strange.  Is it possible you are using an old version of cargo or rust?  Because the error message mentions `oniguruma`, which is not used by any dependency, instead the `onig` crate is renamed to `oniguruma`.

I cannot replicate this issue with a clean environment.

**Comment by maygic23** [comment]
I'm using raspbian (based on debian 9) on raspberrypi (arm architecture). And cargo, rust are from that distro repositories.
rustc:armhf (1.24.1+dfsg1-1\~deb9u2+rpi1, automatic), libstd-rust-dev:armhf (1.24.1+dfsg1-1\~deb9u2+rpi1, automatic), rust-gdb:armhf (1.24.1+dfsg1-1\~deb9u2+rpi1, automatic), libllvm4.0:armhf (1:4.0.1-10+rpi1\~bpo9+1, automatic), libhttp-parser2.1:armhf (2.1-2, automatic), cargo:armhf (0.15.0\~dev-1+rpi1), libstd-rust-1.24:armhf (1.24.1+dfsg1-1~deb9u2+rpi1, automatic)

raspberrypi% cat /etc/os-release                                                                                                           
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"                                                                                               
NAME="Raspbian GNU/Linux"                                                                                                                                    
VERSION_ID="9"                                                                                                                                               
VERSION="9 (stretch)"                                                                                                                    
VERSION_CODENAME=stretch                                                                                                                                     
ID=raspbian                                                                                                                                                  
ID_LIKE=debian                                                                                                                                               HOME_URL="http://www.raspbian.org/"                                          
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"    
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"                                                                             
raspberrypi% uname -a                                                                                                                                        
Linux raspberrypi.home 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

Also if in parsing/Cargo.toml I'll change rev for [dependencies.simple_ast] to the latest commit (26c65b2) then it asks for version required: ^6.0.0. I suppose this is ok, but my rust & cargo are probably too old or something. I'll try installing the latest from github instead of the one from raspbian repository and see if that helps (but I don't like this solution).

**Comment by Noskcaj19** [comment]
Rust 1.24.1 was released in early 2018 and there have been many changes since then, even if dependency resolution could be fixed, I depend on a number of features that were not supported then.

The recommended way of installing outside of the package manager is through [rustup](https://rustup.rs/).
