### ISSUE TITLE
Discord buffer doesn't appear in Weechat

### ISSUE THREAD

**Issue by c0lored** [terminal-discord/weechat-discord#83]
I can successfully set my token and issue /discord connect but I get no feedback, if I issue it again I get "discord already connected". 
I can issue /discord disconnect and do get feed back of "discord: Disconnected"

No additional buffer appears in the Weechat bufferlist. Just the main one.

**Comment by Noskcaj19** [comment]
It sounds like you may be in "irc-mode", where the plugin only joins channels or guilds you have configured, you can try joining a channel with `/discord join <guild-name> [<channel-name>]`

What build are you using?  Because the experimental v3 builds default to irc mode.

**Comment by c0lored** [comment]
> It sounds like you may be in "irc-mode", where the plugin only joins channels or guilds you have configured, you can try joining a channel with `/discord join <guild-name> [<channel-name>]`
> 
> What build are you using? Because the experimental v3 builds default to irc mode.

I was using the version from AUR. I just built it from source

I tried both irc-mode and discord-mode

**Comment by Noskcaj19** [comment]
That's interesting... I'll have to look into that.  The discord library I use is pinned to a fairly old version, that may be causing issues.  Once I have some time I'll look into it.

**Comment by c0lored** [comment]
> That's interesting... I'll have to look into that. The discord library I use is pinned to a fairly old version, that may be causing issues. Once I have some time I'll look into it.

Awesome thanks, Here's a screenshot, just to be thorough. 
If you need logs or anything, let me know!

![image](https://user-images.githubusercontent.com/18104903/91764664-b5c5ed00-eba5-11ea-9f2a-f5430452b1e5.png)

**Comment by Noskcaj19** [comment]
I am unfortunately not able to replicate the issue you have.  If you want to check logs, that might lot.  Unfortunately, one, there is currently no built in logging system, and two, the discord library logs contains lots of personal information. 

If you would like to check the logs, the simplest way would be to apply this patch to master, and run with `RUST_LOG=trace weechat 2>log.txt` (logs will be written to stderr, which is redirected to a file).

If the connection to discord succeeds, there should be a  `Received message {"t":"READY","...` message.

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 7cdee77..d7ea03f 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -22,6 +22,7 @@ crossbeam-channel = "0.4.2"
 regex = "1.3.7"
 indexmap = "1.3.2"
 json = "0.12.4"
+env_logger = "0.7.1"

 [dependencies.parking_lot]
 rev = "046a171"
diff --git a/src/lib.rs b/src/lib.rs
index e872ede..003172c 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -28,6 +28,7 @@ pub struct Discord {
 impl WeechatPlugin for Discord {
     // Note: We cannot use on_main (or plugin_print)
     fn init(weechat: Weechat, args: ArgsWeechat) -> WeechatResult<Self> {
+        env_logger::init();
         let args: Vec<_> = args.collect();

         let _sync_handle = sync::init(&weechat);
```

**Comment by c0lored** [comment]
I found the issues. The log was IMMENSELY helpful. 

I had truncated a character from my token. 

So even on Authentication Failure I was not getting any feed back. Also the "already connected" was misleading as it wasn't actually connected.

**Comment by Noskcaj19** [comment]
That's very interesting.  I will have to investigate why the error is not reported.
