### ISSUE TITLE
Plugin not working anymore ?

### ISSUE THREAD

**Issue by Lertsenem** [terminal-discord/weechat-discord#92]
The plugin was working fine for me until now.

I'm now unable to connect since 2021-03-31 (last message I got was at 23:50). When I use `/discord connect` I get no message at all and no new buffers opening (neither in irc-mode nor in discord-mode). I tried to restart weechat without plugin (`weechat --no-plugin`) and with a default configuration (`weechat -t`). I'm using [this automatic build](https://github.com/terminal-discord/weechat-discord/actions/runs/674484023) for linux (commit e62ad49)

My discord account is still working with the web client, so I can confirm I've not been banned, and my auth token is still the same.

I tried to `/debug set weecord 10` but I could not get any debug info anyway. I don't know if there's another way to do that.

**Comment by Noskcaj19** [comment]
Ok, so I am unable to reproduce the buffers not opening (all of my server buffers open correctly) and all the messages load, however new messages to not appear until the buffer is closed and reopened (the message events are received, but don't seem to be processed. I'll have to try and figure out what's causing that).

Is it server buffers that aren't working,  dm channels, or both?

The version of the discord library being used is very old as well as using a deprecated version of the gateway, which could be causing theses problems.

Unfortunately this version has very limited logging and it's [not exactly easy turn on](https://github.com/terminal-discord/weechat-discord/issues/83#issuecomment-684025322) (And it only logs discord api related events, nothing client level)

**Comment by Lertsenem** [comment]
I've only be using server buffers (specific Guild->channel that I added to my autojoined list) and that's what not working for me anymore. I never tried to use DM channels (and I'm not sure how I can use them?).

I'm not really comfortable with building rust from source, but I guess I'll have to if I want some logs.

In the meantime should I try to upgrade to [this build](https://github.com/terminal-discord/weechat-discord/actions/runs/690793164) on the mk3 branch, or should I stay on master ?

**Comment by Noskcaj19** [comment]
The mk3 branch should have everything master has at this point, and will become the default branch soon (it has no major issues as far as I know), the biggest things that need to be done is revamping the commands (they are kinda clunky right now) and adding usage instructions.

If you would like to try the mk3 branch, the the biggest difference I can think of is you have to join a channel the commands are:
`/discord server add <server_name>` (only needed once per server)
`/discord server autoconnect <server_name>`
`/discord channel autojoin <server_name> <channel_name>`

While the commands will change soon, the config format should not.

Otherwise, I would be happy to make a ci build with logging enabled if you would like to go that route.

**Comment by Lertsenem** [comment]
I'm up for a build with logging enabled if you can provide that.

I'll try the mk3 branch too.

**Comment by Lertsenem** [comment]
I tried the mk3 branch, wiping my weecord config first.

After my `/plugin load weecord` I got a `ignoring \`\`: invalid filter directive` error line, that I ignored.

I set my token like with the master branch using `/discord token 1234678900...`

`/discord server list` does not seem to give me any result. I tried some `/discord server add My_server` but was met with `discord: could not find guild: My_server`. There's no `/discord connect` anymore, is that normal? No new buffer has been created at all, apparently.

**Comment by Noskcaj19** [comment]
The `invalid filter directive` warning is interesting, I'm not sure how that happened.

Secondly, the commands are currently very unintuitive, and is why I need to rework them.
The `server list` command is to list servers you have "joined" (servers need to be "joined"/"added" similar to how you need to add irc servers).  I will either reword those commands or make the output indicate "added" servers and list servers that can be joined.

As for adding the server, did you use tab completion for the server name?  The new version is more strict with respect to special characters and expects tab completion to be used.

**Comment by Lertsenem** [comment]
I did try to use tab completion with `/discord server add <tab>`, but was only proposed irrelevant suggestions (namely: the irc channels I'm in...).

**Comment by Noskcaj19** [comment]
That is.. very odd.  I can only get that to happen if there is extraneous text in the command (i.e. `/discord server add f <tab>` gets irc suggestions)

Also, the master branch should have logging enabled as of commit 8574281 and [build](https://github.com/terminal-discord/weechat-discord/actions/runs/709726972). 
 Run with the environment variable `RUST_LOG=trace,tungstenite::protocol::frame=warn,rustls=warn,h2=warn` to get verbose logging but without most of the needless details.

**Comment by Lertsenem** [comment]
I ran `RUST_LOG=trace,tungstenite::protocol::frame=warn,rustls=warn,h2=warn weechat`

Then, in buffer [1: weechat] :

````
> /discord server add Godot_Engine
> could not find guild: Godot_Engine
> /plugin unload weecord
> Extension "weecord" déchargée
> /plugin load weecord
> discord: Unable to setup logging, trace window will be empty!: a global default trace dispatcher has already been set
> Extension "weecord" chargée
````

(As you may notice I'm french, but I'm not sure that's relevant. "chargée" means "loaded" and "déchargée" means "unloaded").

**Comment by Noskcaj19** [comment]
Sorry, I didn't make it clear, only the master branch will respect RUST_LOG, mk3 uses the config `weecord.general.log_directive` (and will require a different directive)
(Now that I think of it, mk3 probably should use RUST_LOG somehow..)

Also, due to how weechat loads plugins (dylib caching is enabled), mk3 logging fails when reloading the plugin.  weechat must be fully exited, or the `/upgrade` command used.

The "Godot_Engine" server, what is its name in discord?

**Comment by Lertsenem** [comment]
The "Godot_Engine" server, what is its name in discord?
"Godot Engine"

I tried several other writing, and also tried a discord name without white space ("SHOWTIME.").

Just to clarify, I should download the build you linked and try to `/discord token 123`, `/discord connect`, am I right ?

**Comment by Noskcaj19** [comment]
Yes, the build I linked to should be the same as master has been, except it will respect RUST_LOG environment variables.

The mk3 branch no longer has the connect command, to disconnect, the plugin can be unloaded.

**Comment by Noskcaj19** [comment]
Out of curiosity, would you happen to be in a "large" number of servers (maybe more than 20 or so?).  At some point the discord api has seemed to behave differently when large amounts of servers are involved.

**Comment by Lertsenem** [comment]
I'm in exactly 19 servers. :]

I'm using the build you linked, ran:
`RUST_LOG=trace,tungstenite::protocol::frame=warn,rustls=warn,h2=warn weechat`
In [1:weechat] I get
```
> Extensions chargées : alias, buflist, charset, exec, fifo, fset, irc, logger, lua, perl, python, relay, ruby, script, spell, trigger, weecord, xfer
```
Then:

```
> /discord token ABCDEf.12341ab_c_d
> discord: Set Discord token
> /discord connect
[nothing happens]
> /discord disconnect
> discord: Disconnected
> /discord connect
[nothing happens]
> /discord connect
> discord: Already connected
> /discord disconnect
> discord: Disconnected
> /plugin unload weecord
> Extension "weecord" déchargée
> /plugin load libweecord
[crash occurs]
thread '<unnamed>' panicked at 'Logger initialization failed with Logger initialization failed', src/lib.rs:41:37
                                                 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       fatal runtime error: failed to initiate panic, error 5
                                                             [1]    2161488 abort (core dumped)  RUST_LOG=trace,tungstenite::protocol::frame=warn,rustls=warn,h2=warn weechat
```

**Comment by Lertsenem** [comment]
The weird part is it was working fine 2 days ago. Is there a cache of data somewhere for weecord that I could get rid of to start off clean?

**Comment by Noskcaj19** [comment]
Interesting... it should write a log file to your current directory.

There is no cache sadly, although, that does remind me of something I should have thought of earlier.  Your timing lines up pretty closely with the rollout of the new "Stage channels".

A quick test (on mk3) shows that at the presence of stage channel completely breaking loading, so I suspect that may be the issue.

**Comment by Noskcaj19** [comment]
The issue should now be fixed on both branches, if it isn't, feel free to reopen and I'll see what I can do.

**Comment by Lertsenem** [comment]
Yes, it works! Thank you so much!
