### ISSUE TITLE
Slow to deliver message overwrites received message in the interim in the UI

### ISSUE THREAD

**Issue by natrys** [terminal-discord/weechat-discord#95]
Hello, I have switched to the mk3 branch and observing this. Basically:

i) I send a message, but due to presumably network issues the delivery isn't confirmed. The message is still placed on buffer (in a darkened foreground colour).

ii) I receive a message in the mean time, which is placed right after my as of yet undelivered message.

iii) Finally delivery of my message is confirmed. But instead of replacing old line (with dim foreground), the message now with normal foreground replaces the *last* message which is was what I *received*, not sent. And So I can no longer see the message I received, instead see double of what I sent.

On that note, assuming very slow delivery was network issue in first place, I just want to say I used master for a while before on very same network, and hardly even had issue like this.

You might not be able to replicate poor network condition for this though :/

**Comment by Noskcaj19** [comment]
I'm not happy with how weechat-discord handles slow and spotty network connections right now, but it is improving.

I was able to replicate the issue you had, and f9009d4 seems to have fixed it.

**Comment by natrys** [comment]
Thanks for the quick fix. I will use for a day or so, and report back.

**Comment by natrys** [comment]
I believe this problem indeed is fixed, thanks!
